//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class MockApplicant
    {
        public long applicant_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string address_1 { get; set; }
        public string address_2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string reason { get; set; }
        public string story { get; set; }
        public string gender_avatar { get; set; }
        public Nullable<bool> enough_food { get; set; }
        public Nullable<int> houshold_size { get; set; }
        public string insecurity_frequency { get; set; }
        public string illnesses { get; set; }
        public System.DateTime posted { get; set; }
        public string source { get; set; }
        public string county { get; set; }
        public Nullable<bool> applicant_status { get; set; }
        public bool priority_id { get; set; }
        public Nullable<bool> health_insurance { get; set; }
        public string health_plan { get; set; }
        public Nullable<int> children_in_household { get; set; }
        public Nullable<int> seniors_in_household { get; set; }
        public Nullable<bool> job_loss_or_reduced_hours { get; set; }
        public Nullable<bool> medical_transportation { get; set; }
        public Nullable<bool> grocery_transportation { get; set; }
        public Nullable<bool> dental_transportation { get; set; }
        public Nullable<bool> internet_access { get; set; }
        public Nullable<bool> computer_in_home { get; set; }
        public string referral_source { get; set; }
        public Nullable<bool> lives_in_food_desert { get; set; }
        public Nullable<bool> tract_low_income { get; set; }
        public Nullable<double> tract_poverty_rate { get; set; }
        public Nullable<double> tract_median_income { get; set; }
        public string preferred_language { get; set; }
        public Nullable<bool> english_as_second_language { get; set; }
        public string race { get; set; }
        public string ethnicity { get; set; }
        public Nullable<bool> urban { get; set; }
        public string cant_afford_balanced_meals { get; set; }
        public Nullable<bool> skipped_meals { get; set; }
        public string benefits { get; set; }
        public string living_situation_today { get; set; }
        public string problems_with_housing { get; set; }
        public string risk_of_losing_services { get; set; }
        public string want_help_with_employment { get; set; }
        public string how_hard_to_pay_for_basics { get; set; }
        public string income_bracket { get; set; }
        public Nullable<bool> live_with_illness { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string worry_food_run_out { get; set; }
        public string education_level { get; set; }
    }
}
