//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WebApplication2
{
    #region Contexts
    
    /// <summary>`
    /// No Metadata Documentation available.
    /// </summary>
    public partial class internDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new internDBEntities object using the connection string found in the 'internDBEntities' section of the application configuration file.
        /// </summary>
        public internDBEntities() : base("name=internDBEntities", "internDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new internDBEntities object.
        /// </summary>
        public internDBEntities(string connectionString) : base(connectionString, "internDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new internDBEntities object.
        /// </summary>
        public internDBEntities(EntityConnection connection) : base(connection, "internDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MockApplicant> MockApplicants
        {
            get
            {
                if ((_MockApplicants == null))
                {
                    _MockApplicants = base.CreateObjectSet<MockApplicant>("MockApplicants");
                }
                return _MockApplicants;
            }
        }
        private ObjectSet<MockApplicant> _MockApplicants;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mockData> mockDatas
        {
            get
            {
                if ((_mockDatas == null))
                {
                    _mockDatas = base.CreateObjectSet<mockData>("mockDatas");
                }
                return _mockDatas;
            }
        }
        private ObjectSet<mockData> _mockDatas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MockApplicants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMockApplicants(MockApplicant mockApplicant)
        {
            base.AddObject("MockApplicants", mockApplicant);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mockDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomockDatas(mockData mockData)
        {
            base.AddObject("mockDatas", mockData);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="internDBModel", Name="MockApplicant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MockApplicant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MockApplicant object.
        /// </summary>
        /// <param name="applicant_id">Initial value of the applicant_id property.</param>
        /// <param name="first_name">Initial value of the first_name property.</param>
        /// <param name="last_name">Initial value of the last_name property.</param>
        /// <param name="address_1">Initial value of the address_1 property.</param>
        /// <param name="city">Initial value of the city property.</param>
        /// <param name="state">Initial value of the state property.</param>
        /// <param name="zip">Initial value of the zip property.</param>
        /// <param name="posted">Initial value of the posted property.</param>
        /// <param name="priority_id">Initial value of the priority_id property.</param>
        public static MockApplicant CreateMockApplicant(global::System.Int64 applicant_id, global::System.String first_name, global::System.String last_name, global::System.String address_1, global::System.String city, global::System.String state, global::System.String zip, global::System.DateTime posted, global::System.Boolean priority_id)
        {
            MockApplicant mockApplicant = new MockApplicant();
            mockApplicant.applicant_id = applicant_id;
            mockApplicant.first_name = first_name;
            mockApplicant.last_name = last_name;
            mockApplicant.address_1 = address_1;
            mockApplicant.city = city;
            mockApplicant.state = state;
            mockApplicant.zip = zip;
            mockApplicant.posted = posted;
            mockApplicant.priority_id = priority_id;
            return mockApplicant;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 applicant_id
        {
            get
            {
                return _applicant_id;
            }
            set
            {
                if (_applicant_id != value)
                {
                    Onapplicant_idChanging(value);
                    ReportPropertyChanging("applicant_id");
                    _applicant_id = StructuralObject.SetValidValue(value, "applicant_id");
                    ReportPropertyChanged("applicant_id");
                    Onapplicant_idChanged();
                }
            }
        }
        private global::System.Int64 _applicant_id;
        partial void Onapplicant_idChanging(global::System.Int64 value);
        partial void Onapplicant_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String first_name
        {
            get
            {
                return _first_name;
            }
            set
            {
                Onfirst_nameChanging(value);
                ReportPropertyChanging("first_name");
                _first_name = StructuralObject.SetValidValue(value, false, "first_name");
                ReportPropertyChanged("first_name");
                Onfirst_nameChanged();
            }
        }
        private global::System.String _first_name;
        partial void Onfirst_nameChanging(global::System.String value);
        partial void Onfirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String last_name
        {
            get
            {
                return _last_name;
            }
            set
            {
                Onlast_nameChanging(value);
                ReportPropertyChanging("last_name");
                _last_name = StructuralObject.SetValidValue(value, false, "last_name");
                ReportPropertyChanged("last_name");
                Onlast_nameChanged();
            }
        }
        private global::System.String _last_name;
        partial void Onlast_nameChanging(global::System.String value);
        partial void Onlast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address_1
        {
            get
            {
                return _address_1;
            }
            set
            {
                Onaddress_1Changing(value);
                ReportPropertyChanging("address_1");
                _address_1 = StructuralObject.SetValidValue(value, false, "address_1");
                ReportPropertyChanged("address_1");
                Onaddress_1Changed();
            }
        }
        private global::System.String _address_1;
        partial void Onaddress_1Changing(global::System.String value);
        partial void Onaddress_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address_2
        {
            get
            {
                return _address_2;
            }
            set
            {
                Onaddress_2Changing(value);
                ReportPropertyChanging("address_2");
                _address_2 = StructuralObject.SetValidValue(value, true, "address_2");
                ReportPropertyChanged("address_2");
                Onaddress_2Changed();
            }
        }
        private global::System.String _address_2;
        partial void Onaddress_2Changing(global::System.String value);
        partial void Onaddress_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, false, "city");
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, false, "state");
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String zip
        {
            get
            {
                return _zip;
            }
            set
            {
                OnzipChanging(value);
                ReportPropertyChanging("zip");
                _zip = StructuralObject.SetValidValue(value, false, "zip");
                ReportPropertyChanged("zip");
                OnzipChanged();
            }
        }
        private global::System.String _zip;
        partial void OnzipChanging(global::System.String value);
        partial void OnzipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, true, "country");
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true, "phone");
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reason
        {
            get
            {
                return _reason;
            }
            set
            {
                OnreasonChanging(value);
                ReportPropertyChanging("reason");
                _reason = StructuralObject.SetValidValue(value, true, "reason");
                ReportPropertyChanged("reason");
                OnreasonChanged();
            }
        }
        private global::System.String _reason;
        partial void OnreasonChanging(global::System.String value);
        partial void OnreasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String story
        {
            get
            {
                return _story;
            }
            set
            {
                OnstoryChanging(value);
                ReportPropertyChanging("story");
                _story = StructuralObject.SetValidValue(value, true, "story");
                ReportPropertyChanged("story");
                OnstoryChanged();
            }
        }
        private global::System.String _story;
        partial void OnstoryChanging(global::System.String value);
        partial void OnstoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gender_avatar
        {
            get
            {
                return _gender_avatar;
            }
            set
            {
                Ongender_avatarChanging(value);
                ReportPropertyChanging("gender_avatar");
                _gender_avatar = StructuralObject.SetValidValue(value, true, "gender_avatar");
                ReportPropertyChanged("gender_avatar");
                Ongender_avatarChanged();
            }
        }
        private global::System.String _gender_avatar;
        partial void Ongender_avatarChanging(global::System.String value);
        partial void Ongender_avatarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> enough_food
        {
            get
            {
                return _enough_food;
            }
            set
            {
                Onenough_foodChanging(value);
                ReportPropertyChanging("enough_food");
                _enough_food = StructuralObject.SetValidValue(value, "enough_food");
                ReportPropertyChanged("enough_food");
                Onenough_foodChanged();
            }
        }
        private Nullable<global::System.Boolean> _enough_food;
        partial void Onenough_foodChanging(Nullable<global::System.Boolean> value);
        partial void Onenough_foodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> houshold_size
        {
            get
            {
                return _houshold_size;
            }
            set
            {
                Onhoushold_sizeChanging(value);
                ReportPropertyChanging("houshold_size");
                _houshold_size = StructuralObject.SetValidValue(value, "houshold_size");
                ReportPropertyChanged("houshold_size");
                Onhoushold_sizeChanged();
            }
        }
        private Nullable<global::System.Int32> _houshold_size;
        partial void Onhoushold_sizeChanging(Nullable<global::System.Int32> value);
        partial void Onhoushold_sizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String insecurity_frequency
        {
            get
            {
                return _insecurity_frequency;
            }
            set
            {
                Oninsecurity_frequencyChanging(value);
                ReportPropertyChanging("insecurity_frequency");
                _insecurity_frequency = StructuralObject.SetValidValue(value, true, "insecurity_frequency");
                ReportPropertyChanged("insecurity_frequency");
                Oninsecurity_frequencyChanged();
            }
        }
        private global::System.String _insecurity_frequency;
        partial void Oninsecurity_frequencyChanging(global::System.String value);
        partial void Oninsecurity_frequencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String illnesses
        {
            get
            {
                return _illnesses;
            }
            set
            {
                OnillnessesChanging(value);
                ReportPropertyChanging("illnesses");
                _illnesses = StructuralObject.SetValidValue(value, true, "illnesses");
                ReportPropertyChanged("illnesses");
                OnillnessesChanged();
            }
        }
        private global::System.String _illnesses;
        partial void OnillnessesChanging(global::System.String value);
        partial void OnillnessesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime posted
        {
            get
            {
                return _posted;
            }
            set
            {
                OnpostedChanging(value);
                ReportPropertyChanging("posted");
                _posted = StructuralObject.SetValidValue(value, "posted");
                ReportPropertyChanged("posted");
                OnpostedChanged();
            }
        }
        private global::System.DateTime _posted;
        partial void OnpostedChanging(global::System.DateTime value);
        partial void OnpostedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String source
        {
            get
            {
                return _source;
            }
            set
            {
                OnsourceChanging(value);
                ReportPropertyChanging("source");
                _source = StructuralObject.SetValidValue(value, true, "source");
                ReportPropertyChanged("source");
                OnsourceChanged();
            }
        }
        private global::System.String _source;
        partial void OnsourceChanging(global::System.String value);
        partial void OnsourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String county
        {
            get
            {
                return _county;
            }
            set
            {
                OncountyChanging(value);
                ReportPropertyChanging("county");
                _county = StructuralObject.SetValidValue(value, true, "county");
                ReportPropertyChanged("county");
                OncountyChanged();
            }
        }
        private global::System.String _county;
        partial void OncountyChanging(global::System.String value);
        partial void OncountyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> applicant_status
        {
            get
            {
                return _applicant_status;
            }
            set
            {
                Onapplicant_statusChanging(value);
                ReportPropertyChanging("applicant_status");
                _applicant_status = StructuralObject.SetValidValue(value, "applicant_status");
                ReportPropertyChanged("applicant_status");
                Onapplicant_statusChanged();
            }
        }
        private Nullable<global::System.Boolean> _applicant_status;
        partial void Onapplicant_statusChanging(Nullable<global::System.Boolean> value);
        partial void Onapplicant_statusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean priority_id
        {
            get
            {
                return _priority_id;
            }
            set
            {
                Onpriority_idChanging(value);
                ReportPropertyChanging("priority_id");
                _priority_id = StructuralObject.SetValidValue(value, "priority_id");
                ReportPropertyChanged("priority_id");
                Onpriority_idChanged();
            }
        }
        private global::System.Boolean _priority_id;
        partial void Onpriority_idChanging(global::System.Boolean value);
        partial void Onpriority_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> health_insurance
        {
            get
            {
                return _health_insurance;
            }
            set
            {
                Onhealth_insuranceChanging(value);
                ReportPropertyChanging("health_insurance");
                _health_insurance = StructuralObject.SetValidValue(value, "health_insurance");
                ReportPropertyChanged("health_insurance");
                Onhealth_insuranceChanged();
            }
        }
        private Nullable<global::System.Boolean> _health_insurance;
        partial void Onhealth_insuranceChanging(Nullable<global::System.Boolean> value);
        partial void Onhealth_insuranceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String health_plan
        {
            get
            {
                return _health_plan;
            }
            set
            {
                Onhealth_planChanging(value);
                ReportPropertyChanging("health_plan");
                _health_plan = StructuralObject.SetValidValue(value, true, "health_plan");
                ReportPropertyChanged("health_plan");
                Onhealth_planChanged();
            }
        }
        private global::System.String _health_plan;
        partial void Onhealth_planChanging(global::System.String value);
        partial void Onhealth_planChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> children_in_household
        {
            get
            {
                return _children_in_household;
            }
            set
            {
                Onchildren_in_householdChanging(value);
                ReportPropertyChanging("children_in_household");
                _children_in_household = StructuralObject.SetValidValue(value, "children_in_household");
                ReportPropertyChanged("children_in_household");
                Onchildren_in_householdChanged();
            }
        }
        private Nullable<global::System.Int32> _children_in_household;
        partial void Onchildren_in_householdChanging(Nullable<global::System.Int32> value);
        partial void Onchildren_in_householdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> seniors_in_household
        {
            get
            {
                return _seniors_in_household;
            }
            set
            {
                Onseniors_in_householdChanging(value);
                ReportPropertyChanging("seniors_in_household");
                _seniors_in_household = StructuralObject.SetValidValue(value, "seniors_in_household");
                ReportPropertyChanged("seniors_in_household");
                Onseniors_in_householdChanged();
            }
        }
        private Nullable<global::System.Int32> _seniors_in_household;
        partial void Onseniors_in_householdChanging(Nullable<global::System.Int32> value);
        partial void Onseniors_in_householdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> job_loss_or_reduced_hours
        {
            get
            {
                return _job_loss_or_reduced_hours;
            }
            set
            {
                Onjob_loss_or_reduced_hoursChanging(value);
                ReportPropertyChanging("job_loss_or_reduced_hours");
                _job_loss_or_reduced_hours = StructuralObject.SetValidValue(value, "job_loss_or_reduced_hours");
                ReportPropertyChanged("job_loss_or_reduced_hours");
                Onjob_loss_or_reduced_hoursChanged();
            }
        }
        private Nullable<global::System.Boolean> _job_loss_or_reduced_hours;
        partial void Onjob_loss_or_reduced_hoursChanging(Nullable<global::System.Boolean> value);
        partial void Onjob_loss_or_reduced_hoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> medical_transportation
        {
            get
            {
                return _medical_transportation;
            }
            set
            {
                Onmedical_transportationChanging(value);
                ReportPropertyChanging("medical_transportation");
                _medical_transportation = StructuralObject.SetValidValue(value, "medical_transportation");
                ReportPropertyChanged("medical_transportation");
                Onmedical_transportationChanged();
            }
        }
        private Nullable<global::System.Boolean> _medical_transportation;
        partial void Onmedical_transportationChanging(Nullable<global::System.Boolean> value);
        partial void Onmedical_transportationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> grocery_transportation
        {
            get
            {
                return _grocery_transportation;
            }
            set
            {
                Ongrocery_transportationChanging(value);
                ReportPropertyChanging("grocery_transportation");
                _grocery_transportation = StructuralObject.SetValidValue(value, "grocery_transportation");
                ReportPropertyChanged("grocery_transportation");
                Ongrocery_transportationChanged();
            }
        }
        private Nullable<global::System.Boolean> _grocery_transportation;
        partial void Ongrocery_transportationChanging(Nullable<global::System.Boolean> value);
        partial void Ongrocery_transportationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> dental_transportation
        {
            get
            {
                return _dental_transportation;
            }
            set
            {
                Ondental_transportationChanging(value);
                ReportPropertyChanging("dental_transportation");
                _dental_transportation = StructuralObject.SetValidValue(value, "dental_transportation");
                ReportPropertyChanged("dental_transportation");
                Ondental_transportationChanged();
            }
        }
        private Nullable<global::System.Boolean> _dental_transportation;
        partial void Ondental_transportationChanging(Nullable<global::System.Boolean> value);
        partial void Ondental_transportationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> internet_access
        {
            get
            {
                return _internet_access;
            }
            set
            {
                Oninternet_accessChanging(value);
                ReportPropertyChanging("internet_access");
                _internet_access = StructuralObject.SetValidValue(value, "internet_access");
                ReportPropertyChanged("internet_access");
                Oninternet_accessChanged();
            }
        }
        private Nullable<global::System.Boolean> _internet_access;
        partial void Oninternet_accessChanging(Nullable<global::System.Boolean> value);
        partial void Oninternet_accessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> computer_in_home
        {
            get
            {
                return _computer_in_home;
            }
            set
            {
                Oncomputer_in_homeChanging(value);
                ReportPropertyChanging("computer_in_home");
                _computer_in_home = StructuralObject.SetValidValue(value, "computer_in_home");
                ReportPropertyChanged("computer_in_home");
                Oncomputer_in_homeChanged();
            }
        }
        private Nullable<global::System.Boolean> _computer_in_home;
        partial void Oncomputer_in_homeChanging(Nullable<global::System.Boolean> value);
        partial void Oncomputer_in_homeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String referral_source
        {
            get
            {
                return _referral_source;
            }
            set
            {
                Onreferral_sourceChanging(value);
                ReportPropertyChanging("referral_source");
                _referral_source = StructuralObject.SetValidValue(value, true, "referral_source");
                ReportPropertyChanged("referral_source");
                Onreferral_sourceChanged();
            }
        }
        private global::System.String _referral_source;
        partial void Onreferral_sourceChanging(global::System.String value);
        partial void Onreferral_sourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> lives_in_food_desert
        {
            get
            {
                return _lives_in_food_desert;
            }
            set
            {
                Onlives_in_food_desertChanging(value);
                ReportPropertyChanging("lives_in_food_desert");
                _lives_in_food_desert = StructuralObject.SetValidValue(value, "lives_in_food_desert");
                ReportPropertyChanged("lives_in_food_desert");
                Onlives_in_food_desertChanged();
            }
        }
        private Nullable<global::System.Boolean> _lives_in_food_desert;
        partial void Onlives_in_food_desertChanging(Nullable<global::System.Boolean> value);
        partial void Onlives_in_food_desertChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> tract_low_income
        {
            get
            {
                return _tract_low_income;
            }
            set
            {
                Ontract_low_incomeChanging(value);
                ReportPropertyChanging("tract_low_income");
                _tract_low_income = StructuralObject.SetValidValue(value, "tract_low_income");
                ReportPropertyChanged("tract_low_income");
                Ontract_low_incomeChanged();
            }
        }
        private Nullable<global::System.Boolean> _tract_low_income;
        partial void Ontract_low_incomeChanging(Nullable<global::System.Boolean> value);
        partial void Ontract_low_incomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> tract_poverty_rate
        {
            get
            {
                return _tract_poverty_rate;
            }
            set
            {
                Ontract_poverty_rateChanging(value);
                ReportPropertyChanging("tract_poverty_rate");
                _tract_poverty_rate = StructuralObject.SetValidValue(value, "tract_poverty_rate");
                ReportPropertyChanged("tract_poverty_rate");
                Ontract_poverty_rateChanged();
            }
        }
        private Nullable<global::System.Double> _tract_poverty_rate;
        partial void Ontract_poverty_rateChanging(Nullable<global::System.Double> value);
        partial void Ontract_poverty_rateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> tract_median_income
        {
            get
            {
                return _tract_median_income;
            }
            set
            {
                Ontract_median_incomeChanging(value);
                ReportPropertyChanging("tract_median_income");
                _tract_median_income = StructuralObject.SetValidValue(value, "tract_median_income");
                ReportPropertyChanged("tract_median_income");
                Ontract_median_incomeChanged();
            }
        }
        private Nullable<global::System.Double> _tract_median_income;
        partial void Ontract_median_incomeChanging(Nullable<global::System.Double> value);
        partial void Ontract_median_incomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String preferred_language
        {
            get
            {
                return _preferred_language;
            }
            set
            {
                Onpreferred_languageChanging(value);
                ReportPropertyChanging("preferred_language");
                _preferred_language = StructuralObject.SetValidValue(value, true, "preferred_language");
                ReportPropertyChanged("preferred_language");
                Onpreferred_languageChanged();
            }
        }
        private global::System.String _preferred_language;
        partial void Onpreferred_languageChanging(global::System.String value);
        partial void Onpreferred_languageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> english_as_second_language
        {
            get
            {
                return _english_as_second_language;
            }
            set
            {
                Onenglish_as_second_languageChanging(value);
                ReportPropertyChanging("english_as_second_language");
                _english_as_second_language = StructuralObject.SetValidValue(value, "english_as_second_language");
                ReportPropertyChanged("english_as_second_language");
                Onenglish_as_second_languageChanged();
            }
        }
        private Nullable<global::System.Boolean> _english_as_second_language;
        partial void Onenglish_as_second_languageChanging(Nullable<global::System.Boolean> value);
        partial void Onenglish_as_second_languageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String race
        {
            get
            {
                return _race;
            }
            set
            {
                OnraceChanging(value);
                ReportPropertyChanging("race");
                _race = StructuralObject.SetValidValue(value, true, "race");
                ReportPropertyChanged("race");
                OnraceChanged();
            }
        }
        private global::System.String _race;
        partial void OnraceChanging(global::System.String value);
        partial void OnraceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ethnicity
        {
            get
            {
                return _ethnicity;
            }
            set
            {
                OnethnicityChanging(value);
                ReportPropertyChanging("ethnicity");
                _ethnicity = StructuralObject.SetValidValue(value, true, "ethnicity");
                ReportPropertyChanged("ethnicity");
                OnethnicityChanged();
            }
        }
        private global::System.String _ethnicity;
        partial void OnethnicityChanging(global::System.String value);
        partial void OnethnicityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> urban
        {
            get
            {
                return _urban;
            }
            set
            {
                OnurbanChanging(value);
                ReportPropertyChanging("urban");
                _urban = StructuralObject.SetValidValue(value, "urban");
                ReportPropertyChanged("urban");
                OnurbanChanged();
            }
        }
        private Nullable<global::System.Boolean> _urban;
        partial void OnurbanChanging(Nullable<global::System.Boolean> value);
        partial void OnurbanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cant_afford_balanced_meals
        {
            get
            {
                return _cant_afford_balanced_meals;
            }
            set
            {
                Oncant_afford_balanced_mealsChanging(value);
                ReportPropertyChanging("cant_afford_balanced_meals");
                _cant_afford_balanced_meals = StructuralObject.SetValidValue(value, true, "cant_afford_balanced_meals");
                ReportPropertyChanged("cant_afford_balanced_meals");
                Oncant_afford_balanced_mealsChanged();
            }
        }
        private global::System.String _cant_afford_balanced_meals;
        partial void Oncant_afford_balanced_mealsChanging(global::System.String value);
        partial void Oncant_afford_balanced_mealsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> skipped_meals
        {
            get
            {
                return _skipped_meals;
            }
            set
            {
                Onskipped_mealsChanging(value);
                ReportPropertyChanging("skipped_meals");
                _skipped_meals = StructuralObject.SetValidValue(value, "skipped_meals");
                ReportPropertyChanged("skipped_meals");
                Onskipped_mealsChanged();
            }
        }
        private Nullable<global::System.Boolean> _skipped_meals;
        partial void Onskipped_mealsChanging(Nullable<global::System.Boolean> value);
        partial void Onskipped_mealsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String benefits
        {
            get
            {
                return _benefits;
            }
            set
            {
                OnbenefitsChanging(value);
                ReportPropertyChanging("benefits");
                _benefits = StructuralObject.SetValidValue(value, true, "benefits");
                ReportPropertyChanged("benefits");
                OnbenefitsChanged();
            }
        }
        private global::System.String _benefits;
        partial void OnbenefitsChanging(global::System.String value);
        partial void OnbenefitsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String living_situation_today
        {
            get
            {
                return _living_situation_today;
            }
            set
            {
                Onliving_situation_todayChanging(value);
                ReportPropertyChanging("living_situation_today");
                _living_situation_today = StructuralObject.SetValidValue(value, true, "living_situation_today");
                ReportPropertyChanged("living_situation_today");
                Onliving_situation_todayChanged();
            }
        }
        private global::System.String _living_situation_today;
        partial void Onliving_situation_todayChanging(global::System.String value);
        partial void Onliving_situation_todayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String problems_with_housing
        {
            get
            {
                return _problems_with_housing;
            }
            set
            {
                Onproblems_with_housingChanging(value);
                ReportPropertyChanging("problems_with_housing");
                _problems_with_housing = StructuralObject.SetValidValue(value, true, "problems_with_housing");
                ReportPropertyChanged("problems_with_housing");
                Onproblems_with_housingChanged();
            }
        }
        private global::System.String _problems_with_housing;
        partial void Onproblems_with_housingChanging(global::System.String value);
        partial void Onproblems_with_housingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String risk_of_losing_services
        {
            get
            {
                return _risk_of_losing_services;
            }
            set
            {
                Onrisk_of_losing_servicesChanging(value);
                ReportPropertyChanging("risk_of_losing_services");
                _risk_of_losing_services = StructuralObject.SetValidValue(value, true, "risk_of_losing_services");
                ReportPropertyChanged("risk_of_losing_services");
                Onrisk_of_losing_servicesChanged();
            }
        }
        private global::System.String _risk_of_losing_services;
        partial void Onrisk_of_losing_servicesChanging(global::System.String value);
        partial void Onrisk_of_losing_servicesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String want_help_with_employment
        {
            get
            {
                return _want_help_with_employment;
            }
            set
            {
                Onwant_help_with_employmentChanging(value);
                ReportPropertyChanging("want_help_with_employment");
                _want_help_with_employment = StructuralObject.SetValidValue(value, true, "want_help_with_employment");
                ReportPropertyChanged("want_help_with_employment");
                Onwant_help_with_employmentChanged();
            }
        }
        private global::System.String _want_help_with_employment;
        partial void Onwant_help_with_employmentChanging(global::System.String value);
        partial void Onwant_help_with_employmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String how_hard_to_pay_for_basics
        {
            get
            {
                return _how_hard_to_pay_for_basics;
            }
            set
            {
                Onhow_hard_to_pay_for_basicsChanging(value);
                ReportPropertyChanging("how_hard_to_pay_for_basics");
                _how_hard_to_pay_for_basics = StructuralObject.SetValidValue(value, true, "how_hard_to_pay_for_basics");
                ReportPropertyChanged("how_hard_to_pay_for_basics");
                Onhow_hard_to_pay_for_basicsChanged();
            }
        }
        private global::System.String _how_hard_to_pay_for_basics;
        partial void Onhow_hard_to_pay_for_basicsChanging(global::System.String value);
        partial void Onhow_hard_to_pay_for_basicsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String income_bracket
        {
            get
            {
                return _income_bracket;
            }
            set
            {
                Onincome_bracketChanging(value);
                ReportPropertyChanging("income_bracket");
                _income_bracket = StructuralObject.SetValidValue(value, true, "income_bracket");
                ReportPropertyChanged("income_bracket");
                Onincome_bracketChanged();
            }
        }
        private global::System.String _income_bracket;
        partial void Onincome_bracketChanging(global::System.String value);
        partial void Onincome_bracketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> live_with_illness
        {
            get
            {
                return _live_with_illness;
            }
            set
            {
                Onlive_with_illnessChanging(value);
                ReportPropertyChanging("live_with_illness");
                _live_with_illness = StructuralObject.SetValidValue(value, "live_with_illness");
                ReportPropertyChanged("live_with_illness");
                Onlive_with_illnessChanged();
            }
        }
        private Nullable<global::System.Boolean> _live_with_illness;
        partial void Onlive_with_illnessChanging(Nullable<global::System.Boolean> value);
        partial void Onlive_with_illnessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_of_birth
        {
            get
            {
                return _date_of_birth;
            }
            set
            {
                Ondate_of_birthChanging(value);
                ReportPropertyChanging("date_of_birth");
                _date_of_birth = StructuralObject.SetValidValue(value, "date_of_birth");
                ReportPropertyChanged("date_of_birth");
                Ondate_of_birthChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_of_birth;
        partial void Ondate_of_birthChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_of_birthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String worry_food_run_out
        {
            get
            {
                return _worry_food_run_out;
            }
            set
            {
                Onworry_food_run_outChanging(value);
                ReportPropertyChanging("worry_food_run_out");
                _worry_food_run_out = StructuralObject.SetValidValue(value, true, "worry_food_run_out");
                ReportPropertyChanged("worry_food_run_out");
                Onworry_food_run_outChanged();
            }
        }
        private global::System.String _worry_food_run_out;
        partial void Onworry_food_run_outChanging(global::System.String value);
        partial void Onworry_food_run_outChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String education_level
        {
            get
            {
                return _education_level;
            }
            set
            {
                Oneducation_levelChanging(value);
                ReportPropertyChanging("education_level");
                _education_level = StructuralObject.SetValidValue(value, true, "education_level");
                ReportPropertyChanged("education_level");
                Oneducation_levelChanged();
            }
        }
        private global::System.String _education_level;
        partial void Oneducation_levelChanging(global::System.String value);
        partial void Oneducation_levelChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="internDBModel", Name="mockData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mockData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mockData object.
        /// </summary>
        /// <param name="applicant_id">Initial value of the applicant_id property.</param>
        /// <param name="first_name">Initial value of the first_name property.</param>
        /// <param name="last_name">Initial value of the last_name property.</param>
        /// <param name="address_1">Initial value of the address_1 property.</param>
        /// <param name="address_2">Initial value of the address_2 property.</param>
        /// <param name="city">Initial value of the city property.</param>
        /// <param name="country">Initial value of the country property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="reason">Initial value of the reason property.</param>
        /// <param name="story">Initial value of the story property.</param>
        /// <param name="gender_avatar">Initial value of the gender_avatar property.</param>
        /// <param name="enough_food">Initial value of the enough_food property.</param>
        /// <param name="household_size">Initial value of the household_size property.</param>
        /// <param name="insecurity_frequency">Initial value of the insecurity_frequency property.</param>
        /// <param name="illnesses">Initial value of the illnesses property.</param>
        /// <param name="posted">Initial value of the posted property.</param>
        /// <param name="source">Initial value of the source property.</param>
        /// <param name="applicant_status">Initial value of the applicant_status property.</param>
        /// <param name="priority_id">Initial value of the priority_id property.</param>
        /// <param name="health_insurance">Initial value of the health_insurance property.</param>
        /// <param name="health_plan">Initial value of the health_plan property.</param>
        /// <param name="children_in_household">Initial value of the children_in_household property.</param>
        /// <param name="seniors_in_household">Initial value of the seniors_in_household property.</param>
        /// <param name="job_loss_or_reduced_hours">Initial value of the job_loss_or_reduced_hours property.</param>
        /// <param name="medical_transportation">Initial value of the medical_transportation property.</param>
        /// <param name="grocery_transportation">Initial value of the grocery_transportation property.</param>
        /// <param name="dental_transportation">Initial value of the dental_transportation property.</param>
        public static mockData CreatemockData(global::System.Int16 applicant_id, global::System.String first_name, global::System.String last_name, global::System.String address_1, global::System.String address_2, global::System.String city, global::System.String country, global::System.String phone, global::System.String email, global::System.String reason, global::System.String story, global::System.String gender_avatar, global::System.Boolean enough_food, global::System.Byte household_size, global::System.String insecurity_frequency, global::System.String illnesses, global::System.Boolean posted, global::System.String source, global::System.String applicant_status, global::System.Byte priority_id, global::System.Boolean health_insurance, global::System.String health_plan, global::System.Byte children_in_household, global::System.Byte seniors_in_household, global::System.Boolean job_loss_or_reduced_hours, global::System.Boolean medical_transportation, global::System.Boolean grocery_transportation, global::System.Boolean dental_transportation)
        {
            mockData mockData = new mockData();
            mockData.applicant_id = applicant_id;
            mockData.first_name = first_name;
            mockData.last_name = last_name;
            mockData.address_1 = address_1;
            mockData.address_2 = address_2;
            mockData.city = city;
            mockData.country = country;
            mockData.phone = phone;
            mockData.email = email;
            mockData.reason = reason;
            mockData.story = story;
            mockData.gender_avatar = gender_avatar;
            mockData.enough_food = enough_food;
            mockData.household_size = household_size;
            mockData.insecurity_frequency = insecurity_frequency;
            mockData.illnesses = illnesses;
            mockData.posted = posted;
            mockData.source = source;
            mockData.applicant_status = applicant_status;
            mockData.priority_id = priority_id;
            mockData.health_insurance = health_insurance;
            mockData.health_plan = health_plan;
            mockData.children_in_household = children_in_household;
            mockData.seniors_in_household = seniors_in_household;
            mockData.job_loss_or_reduced_hours = job_loss_or_reduced_hours;
            mockData.medical_transportation = medical_transportation;
            mockData.grocery_transportation = grocery_transportation;
            mockData.dental_transportation = dental_transportation;
            return mockData;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 applicant_id
        {
            get
            {
                return _applicant_id;
            }
            set
            {
                if (_applicant_id != value)
                {
                    Onapplicant_idChanging(value);
                    ReportPropertyChanging("applicant_id");
                    _applicant_id = StructuralObject.SetValidValue(value, "applicant_id");
                    ReportPropertyChanged("applicant_id");
                    Onapplicant_idChanged();
                }
            }
        }
        private global::System.Int16 _applicant_id;
        partial void Onapplicant_idChanging(global::System.Int16 value);
        partial void Onapplicant_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String first_name
        {
            get
            {
                return _first_name;
            }
            set
            {
                if (_first_name != value)
                {
                    Onfirst_nameChanging(value);
                    ReportPropertyChanging("first_name");
                    _first_name = StructuralObject.SetValidValue(value, false, "first_name");
                    ReportPropertyChanged("first_name");
                    Onfirst_nameChanged();
                }
            }
        }
        private global::System.String _first_name;
        partial void Onfirst_nameChanging(global::System.String value);
        partial void Onfirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String last_name
        {
            get
            {
                return _last_name;
            }
            set
            {
                if (_last_name != value)
                {
                    Onlast_nameChanging(value);
                    ReportPropertyChanging("last_name");
                    _last_name = StructuralObject.SetValidValue(value, false, "last_name");
                    ReportPropertyChanged("last_name");
                    Onlast_nameChanged();
                }
            }
        }
        private global::System.String _last_name;
        partial void Onlast_nameChanging(global::System.String value);
        partial void Onlast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address_1
        {
            get
            {
                return _address_1;
            }
            set
            {
                if (_address_1 != value)
                {
                    Onaddress_1Changing(value);
                    ReportPropertyChanging("address_1");
                    _address_1 = StructuralObject.SetValidValue(value, false, "address_1");
                    ReportPropertyChanged("address_1");
                    Onaddress_1Changed();
                }
            }
        }
        private global::System.String _address_1;
        partial void Onaddress_1Changing(global::System.String value);
        partial void Onaddress_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address_2
        {
            get
            {
                return _address_2;
            }
            set
            {
                if (_address_2 != value)
                {
                    Onaddress_2Changing(value);
                    ReportPropertyChanging("address_2");
                    _address_2 = StructuralObject.SetValidValue(value, false, "address_2");
                    ReportPropertyChanged("address_2");
                    Onaddress_2Changed();
                }
            }
        }
        private global::System.String _address_2;
        partial void Onaddress_2Changing(global::System.String value);
        partial void Onaddress_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                if (_city != value)
                {
                    OncityChanging(value);
                    ReportPropertyChanging("city");
                    _city = StructuralObject.SetValidValue(value, false, "city");
                    ReportPropertyChanged("city");
                    OncityChanged();
                }
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, true, "state");
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String zip
        {
            get
            {
                return _zip;
            }
            set
            {
                OnzipChanging(value);
                ReportPropertyChanging("zip");
                _zip = StructuralObject.SetValidValue(value, true, "zip");
                ReportPropertyChanged("zip");
                OnzipChanged();
            }
        }
        private global::System.String _zip;
        partial void OnzipChanging(global::System.String value);
        partial void OnzipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                if (_country != value)
                {
                    OncountryChanging(value);
                    ReportPropertyChanging("country");
                    _country = StructuralObject.SetValidValue(value, false, "country");
                    ReportPropertyChanged("country");
                    OncountryChanged();
                }
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                if (_phone != value)
                {
                    OnphoneChanging(value);
                    ReportPropertyChanging("phone");
                    _phone = StructuralObject.SetValidValue(value, false, "phone");
                    ReportPropertyChanged("phone");
                    OnphoneChanged();
                }
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                if (_email != value)
                {
                    OnemailChanging(value);
                    ReportPropertyChanging("email");
                    _email = StructuralObject.SetValidValue(value, false, "email");
                    ReportPropertyChanged("email");
                    OnemailChanged();
                }
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String reason
        {
            get
            {
                return _reason;
            }
            set
            {
                if (_reason != value)
                {
                    OnreasonChanging(value);
                    ReportPropertyChanging("reason");
                    _reason = StructuralObject.SetValidValue(value, false, "reason");
                    ReportPropertyChanged("reason");
                    OnreasonChanged();
                }
            }
        }
        private global::System.String _reason;
        partial void OnreasonChanging(global::System.String value);
        partial void OnreasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String story
        {
            get
            {
                return _story;
            }
            set
            {
                if (_story != value)
                {
                    OnstoryChanging(value);
                    ReportPropertyChanging("story");
                    _story = StructuralObject.SetValidValue(value, false, "story");
                    ReportPropertyChanged("story");
                    OnstoryChanged();
                }
            }
        }
        private global::System.String _story;
        partial void OnstoryChanging(global::System.String value);
        partial void OnstoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gender_avatar
        {
            get
            {
                return _gender_avatar;
            }
            set
            {
                if (_gender_avatar != value)
                {
                    Ongender_avatarChanging(value);
                    ReportPropertyChanging("gender_avatar");
                    _gender_avatar = StructuralObject.SetValidValue(value, false, "gender_avatar");
                    ReportPropertyChanged("gender_avatar");
                    Ongender_avatarChanged();
                }
            }
        }
        private global::System.String _gender_avatar;
        partial void Ongender_avatarChanging(global::System.String value);
        partial void Ongender_avatarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean enough_food
        {
            get
            {
                return _enough_food;
            }
            set
            {
                if (_enough_food != value)
                {
                    Onenough_foodChanging(value);
                    ReportPropertyChanging("enough_food");
                    _enough_food = StructuralObject.SetValidValue(value, "enough_food");
                    ReportPropertyChanged("enough_food");
                    Onenough_foodChanged();
                }
            }
        }
        private global::System.Boolean _enough_food;
        partial void Onenough_foodChanging(global::System.Boolean value);
        partial void Onenough_foodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte household_size
        {
            get
            {
                return _household_size;
            }
            set
            {
                if (_household_size != value)
                {
                    Onhousehold_sizeChanging(value);
                    ReportPropertyChanging("household_size");
                    _household_size = StructuralObject.SetValidValue(value, "household_size");
                    ReportPropertyChanged("household_size");
                    Onhousehold_sizeChanged();
                }
            }
        }
        private global::System.Byte _household_size;
        partial void Onhousehold_sizeChanging(global::System.Byte value);
        partial void Onhousehold_sizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String insecurity_frequency
        {
            get
            {
                return _insecurity_frequency;
            }
            set
            {
                if (_insecurity_frequency != value)
                {
                    Oninsecurity_frequencyChanging(value);
                    ReportPropertyChanging("insecurity_frequency");
                    _insecurity_frequency = StructuralObject.SetValidValue(value, false, "insecurity_frequency");
                    ReportPropertyChanged("insecurity_frequency");
                    Oninsecurity_frequencyChanged();
                }
            }
        }
        private global::System.String _insecurity_frequency;
        partial void Oninsecurity_frequencyChanging(global::System.String value);
        partial void Oninsecurity_frequencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String illnesses
        {
            get
            {
                return _illnesses;
            }
            set
            {
                if (_illnesses != value)
                {
                    OnillnessesChanging(value);
                    ReportPropertyChanging("illnesses");
                    _illnesses = StructuralObject.SetValidValue(value, false, "illnesses");
                    ReportPropertyChanged("illnesses");
                    OnillnessesChanged();
                }
            }
        }
        private global::System.String _illnesses;
        partial void OnillnessesChanging(global::System.String value);
        partial void OnillnessesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean posted
        {
            get
            {
                return _posted;
            }
            set
            {
                if (_posted != value)
                {
                    OnpostedChanging(value);
                    ReportPropertyChanging("posted");
                    _posted = StructuralObject.SetValidValue(value, "posted");
                    ReportPropertyChanged("posted");
                    OnpostedChanged();
                }
            }
        }
        private global::System.Boolean _posted;
        partial void OnpostedChanging(global::System.Boolean value);
        partial void OnpostedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String source
        {
            get
            {
                return _source;
            }
            set
            {
                if (_source != value)
                {
                    OnsourceChanging(value);
                    ReportPropertyChanging("source");
                    _source = StructuralObject.SetValidValue(value, false, "source");
                    ReportPropertyChanged("source");
                    OnsourceChanged();
                }
            }
        }
        private global::System.String _source;
        partial void OnsourceChanging(global::System.String value);
        partial void OnsourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String applicant_status
        {
            get
            {
                return _applicant_status;
            }
            set
            {
                if (_applicant_status != value)
                {
                    Onapplicant_statusChanging(value);
                    ReportPropertyChanging("applicant_status");
                    _applicant_status = StructuralObject.SetValidValue(value, false, "applicant_status");
                    ReportPropertyChanged("applicant_status");
                    Onapplicant_statusChanged();
                }
            }
        }
        private global::System.String _applicant_status;
        partial void Onapplicant_statusChanging(global::System.String value);
        partial void Onapplicant_statusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte priority_id
        {
            get
            {
                return _priority_id;
            }
            set
            {
                if (_priority_id != value)
                {
                    Onpriority_idChanging(value);
                    ReportPropertyChanging("priority_id");
                    _priority_id = StructuralObject.SetValidValue(value, "priority_id");
                    ReportPropertyChanged("priority_id");
                    Onpriority_idChanged();
                }
            }
        }
        private global::System.Byte _priority_id;
        partial void Onpriority_idChanging(global::System.Byte value);
        partial void Onpriority_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean health_insurance
        {
            get
            {
                return _health_insurance;
            }
            set
            {
                if (_health_insurance != value)
                {
                    Onhealth_insuranceChanging(value);
                    ReportPropertyChanging("health_insurance");
                    _health_insurance = StructuralObject.SetValidValue(value, "health_insurance");
                    ReportPropertyChanged("health_insurance");
                    Onhealth_insuranceChanged();
                }
            }
        }
        private global::System.Boolean _health_insurance;
        partial void Onhealth_insuranceChanging(global::System.Boolean value);
        partial void Onhealth_insuranceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String health_plan
        {
            get
            {
                return _health_plan;
            }
            set
            {
                if (_health_plan != value)
                {
                    Onhealth_planChanging(value);
                    ReportPropertyChanging("health_plan");
                    _health_plan = StructuralObject.SetValidValue(value, false, "health_plan");
                    ReportPropertyChanged("health_plan");
                    Onhealth_planChanged();
                }
            }
        }
        private global::System.String _health_plan;
        partial void Onhealth_planChanging(global::System.String value);
        partial void Onhealth_planChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte children_in_household
        {
            get
            {
                return _children_in_household;
            }
            set
            {
                if (_children_in_household != value)
                {
                    Onchildren_in_householdChanging(value);
                    ReportPropertyChanging("children_in_household");
                    _children_in_household = StructuralObject.SetValidValue(value, "children_in_household");
                    ReportPropertyChanged("children_in_household");
                    Onchildren_in_householdChanged();
                }
            }
        }
        private global::System.Byte _children_in_household;
        partial void Onchildren_in_householdChanging(global::System.Byte value);
        partial void Onchildren_in_householdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte seniors_in_household
        {
            get
            {
                return _seniors_in_household;
            }
            set
            {
                if (_seniors_in_household != value)
                {
                    Onseniors_in_householdChanging(value);
                    ReportPropertyChanging("seniors_in_household");
                    _seniors_in_household = StructuralObject.SetValidValue(value, "seniors_in_household");
                    ReportPropertyChanged("seniors_in_household");
                    Onseniors_in_householdChanged();
                }
            }
        }
        private global::System.Byte _seniors_in_household;
        partial void Onseniors_in_householdChanging(global::System.Byte value);
        partial void Onseniors_in_householdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean job_loss_or_reduced_hours
        {
            get
            {
                return _job_loss_or_reduced_hours;
            }
            set
            {
                if (_job_loss_or_reduced_hours != value)
                {
                    Onjob_loss_or_reduced_hoursChanging(value);
                    ReportPropertyChanging("job_loss_or_reduced_hours");
                    _job_loss_or_reduced_hours = StructuralObject.SetValidValue(value, "job_loss_or_reduced_hours");
                    ReportPropertyChanged("job_loss_or_reduced_hours");
                    Onjob_loss_or_reduced_hoursChanged();
                }
            }
        }
        private global::System.Boolean _job_loss_or_reduced_hours;
        partial void Onjob_loss_or_reduced_hoursChanging(global::System.Boolean value);
        partial void Onjob_loss_or_reduced_hoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean medical_transportation
        {
            get
            {
                return _medical_transportation;
            }
            set
            {
                if (_medical_transportation != value)
                {
                    Onmedical_transportationChanging(value);
                    ReportPropertyChanging("medical_transportation");
                    _medical_transportation = StructuralObject.SetValidValue(value, "medical_transportation");
                    ReportPropertyChanged("medical_transportation");
                    Onmedical_transportationChanged();
                }
            }
        }
        private global::System.Boolean _medical_transportation;
        partial void Onmedical_transportationChanging(global::System.Boolean value);
        partial void Onmedical_transportationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean grocery_transportation
        {
            get
            {
                return _grocery_transportation;
            }
            set
            {
                if (_grocery_transportation != value)
                {
                    Ongrocery_transportationChanging(value);
                    ReportPropertyChanging("grocery_transportation");
                    _grocery_transportation = StructuralObject.SetValidValue(value, "grocery_transportation");
                    ReportPropertyChanged("grocery_transportation");
                    Ongrocery_transportationChanged();
                }
            }
        }
        private global::System.Boolean _grocery_transportation;
        partial void Ongrocery_transportationChanging(global::System.Boolean value);
        partial void Ongrocery_transportationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean dental_transportation
        {
            get
            {
                return _dental_transportation;
            }
            set
            {
                if (_dental_transportation != value)
                {
                    Ondental_transportationChanging(value);
                    ReportPropertyChanging("dental_transportation");
                    _dental_transportation = StructuralObject.SetValidValue(value, "dental_transportation");
                    ReportPropertyChanged("dental_transportation");
                    Ondental_transportationChanged();
                }
            }
        }
        private global::System.Boolean _dental_transportation;
        partial void Ondental_transportationChanging(global::System.Boolean value);
        partial void Ondental_transportationChanged();

        #endregion

    }

    #endregion

}
